server:
  port: ${PORT:9023}

bsd:
  frontEndAppUrl: http://localhost:7358
  frontendAppIndexRootUrl: http://localhost:8080/app/public

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/

logging:
  level:
    ROOT: INFO
    org.springframework.data.rest.webmvc: 'DEBUG'
    org.springframework.boot.autoconfigure.security: 'WARN'
    org.springframework.context.support: 'WARN'
    org.springframework.jdbc.datasource: 'WARN'
    org.springframework.boot.context: 'WARN'
    org.springframework.security.web: 'WARN'
    org.springframework.http: 'INFO'
    org.springframework.scheduling.concurrent: 'WARN'
    org.springframework.beans.factory.config: 'WARN'
    org.springframework.integration.config: 'WARN'
    org.springframework.web.servlet.mvc.method.annotation: 'WARN'
    org.springframework.beans.factory.support: 'WARN'

---
# For deployment in Docker containers
spring:
  profiles: docker
  oauth2:
    resource:
      userInfoUri: http://authentication/security-sso-service/uaa/user

eureka:
  instance:
    preferIpAddress: true
#    hostname: gateway
#    virtualHostName: gateway
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    # Default values comes from org.springframework.cloud.netflix.eurek.EurekaClientConfigBean
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5

logging:
  level:
    ROOT: INFO