server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

---
# For deployment in Docker containers
spring:
  profiles: docker

logging:
  level:
    ROOT: INFO