server:
  port: ${PORT:0}

spring:
  jpa:
    generate-ddl: true
  oauth2:
    resource:
      userInfoUri: http://localhost:9023/security-sso-service/uaa/user

eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/

logging:
  level:
    ROOT: INFO
    org.springframework.data.rest.webmvc: 'INFO'
    org.springframework.boot.autoconfigure.security: 'WARN'
    org.springframework.context.support: 'WARN'
    org.springframework.jdbc.datasource: 'WARN'
    org.springframework.boot.context: 'WARN'
    org.springframework.security.web: 'WARN'
    org.springframework.http: 'WARN'
    org.springframework.scheduling.concurrent: 'WARN'
    org.springframework.beans.factory.config: 'WARN'
    org.springframework.integration.config: 'WARN'
    org.springframework.web.servlet.mvc.method.annotation: 'WARN'
    org.springframework.beans.factory.support: 'WARN'

database:
  driver: 'com.mysql.jdbc.Driver'
  url: 'jdbc:mysql://localhost:3306/poc'
  username: 'root'
  password: 'jammal123'

hibernate:
  dialect: 'org.hibernate.dialect.MySQL5Dialect'
  show_sql: true
  hbm2ddl:
    auto: 'update' #create-drop

entitymanager:
  packagesToScan: com.op.service.portal.model

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80
