
server:
  port: ${PORT:0}

spring:
  jpa:
    generate-ddl: true


eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/

database:
  driver: 'com.mysql.jdbc.Driver'
  url: 'jdbc:mysql://localhost:3306/poc'
  username: 'root'
  password: 'jammal123'

hibernate:
  dialect: 'org.hibernate.dialect.MySQL5Dialect'
  show_sql: true
  hbm2ddl:
    auto: 'update' #create-drop

entitymanager:
  packagesToScan: com.op.service.domain.model

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80
